import type { Redirect } from "next/dist/lib/load-custom-routes";

export const legacyRedirects: Redirect[] = [
  { source: "/ES/Inicio", destination: "/", permanent: true },
  { source: "/ES/Inicio/", destination: "/", permanent: true },
  { source: "/ES/Productos", destination: "/productos", permanent: true },
  { source: "/ES/Productos/", destination: "/productos", permanent: true },
  { source: "/ES/Productos/:path*", destination: "/productos", permanent: true },
  { source: "/ES/Campanyas", destination: "/campanas", permanent: true },
  { source: "/ES/Campanyas/", destination: "/campanas", permanent: true },
  { source: "/ES/Calidad", destination: "/calidad", permanent: true },
  { source: "/ES/Calidad/", destination: "/calidad", permanent: true },
  { source: "/ES/Colaboradores", destination: "/colaboradores", permanent: true },
  { source: "/ES/Colaboradores/", destination: "/colaboradores", permanent: true },
  { source: "/ES/Contacto", destination: "/contacto", permanent: true },
  { source: "/ES/Contacto/", destination: "/contacto", permanent: true },
  { source: "/ES/Nosotros", destination: "/nosotros", permanent: true },
  { source: "/ES/Nosotros/", destination: "/nosotros", permanent: true },
  { source: "/ES/Tienda-online/:path*", destination: "/productos", permanent: true },
  { source: "/EN", destination: "/en", permanent: true },
  { source: "/EN/", destination: "/en", permanent: true },
  { source: "/EN/Inicio", destination: "/en", permanent: true },
  { source: "/EN/Inicio/", destination: "/en", permanent: true },
  { source: "/EN/Products", destination: "/en/productos", permanent: true },
  { source: "/EN/Products/", destination: "/en/productos", permanent: true },
  { source: "/EN/Quality", destination: "/en/calidad", permanent: true },
  { source: "/EN/Quality/", destination: "/en/calidad", permanent: true },
  { source: "/EN/Partners", destination: "/en/colaboradores", permanent: true },
  { source: "/EN/Partners/", destination: "/en/colaboradores", permanent: true },
  { source: "/EN/Contact", destination: "/en/contacto", permanent: true },
  { source: "/EN/Contact/", destination: "/en/contacto", permanent: true },
  { source: "/EN/About", destination: "/en/nosotros", permanent: true },
  { source: "/EN/About/", destination: "/en/nosotros", permanent: true },
];
